# Generated by Django 2.1.3 on 2018-12-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20181205_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=3)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto')),
            ],
        ),
    ]
